/*
lable:显示内容
value:得奖代码
（得奖代码以X为开头的为统计XFlag的同一组，
得奖代码以Y为开头的为统计YFlag的同一组， 
不以X开头的为统计Flag的同一组）
*/
var ccData = [
{ "lable": '一等奖(51)', "value": 'J一等奖' },
{ "lable": '二等奖(102)', "value": 'J二等奖' },
{ "lable": '阳光普照奖', "value": 'J阳光普照奖' },

{ "lable": '团圆一家亲', "value": 'X团圆一家亲' },
{ "lable": '好运源源不断', "value": 'X好运源源不断' },
{ "lable": '壹卡会赞助一等奖', "value": 'X壹卡会1' },
{ "lable": '壹卡会赞助二等奖', "value": 'X壹卡会2' },
{ "lable": '壹卡会赞助三等奖', "value": 'X壹卡会3' },

{ "lable": '1号店赞助一等奖', "value": 'Y1号店1' },
{ "lable": '1号店赞助二等奖', "value": 'Y1号店2' },
{ "lable": '1号店赞助三等奖', "value": 'Y1号店3' },


{ "lable": '过滤掉个位', "value": 'F0001' }, //过滤约定标识符 
{"lable": '过滤掉十位', "value": 'F0010' }, //过滤约定标识符 
{"lable": '过滤掉百位', "value": 'F0100' }, //过滤约定标识符 
{"lable": '过滤掉千位', "value": 'F1000'}//过滤约定标识符 
];

/*过滤位
ID:序号，过滤数；
Name:    显示名称；
Flag_0001:个位  (-1:不参与过滤,0：未过滤)；
Flag_0010:十位  (-1:不参与过滤,0：未过滤)；
Flag_0100:百位  (-1:不参与过滤,0：未过滤)；
Flag_1000:千位  (-1:不参与过滤,0：未过滤)；
*/
var bitPool = [{ ID: 0, Name: "0", Flag_0001: "-1", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" },
            { ID: 1, Name: "1", Flag_0001: "-1", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" },
            { ID: 2, Name: "2", Flag_0001: "-1", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" },
            { ID: 3, Name: "3", Flag_0001: "0", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" },
            { ID: 4, Name: "4", Flag_0001: "0", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" },
            { ID: 5, Name: "5", Flag_0001: "0", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" },
            { ID: 6, Name: "6", Flag_0001: "0", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" },
            { ID: 7, Name: "7", Flag_0001: "0", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" },
            { ID: 8, Name: "8", Flag_0001: "0", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" },
            { ID: 9, Name: "9", Flag_0001: "0", Flag_0010: "0", Flag_0100: "0", Flag_1000: "0" }
                ];


/*是否大数字抽奖  范围{1--- MaxbigNumber}
如果设置为 true,则启用最大抽奖数字
如果设置为 false,则启用 luckydraw_sourcePool组别
*/
var IsAutoBigNumber = false;

/*最大抽奖数字*/
var MaxbigNumber = 5578;


/*
ID:序号；
Name:显示名称；
Flag:同组只能抽一次字段(-1:不参与抽奖,0：未抽，1-N：中奖等级)；
XFlag:同组只能抽一次字段(-1:不参与抽奖,0：未抽，X1-XN：中奖等级)；
YFlag:同组只能抽一次字段(-1:不参与抽奖,0：未抽，Y1-YN：中奖等级)；
*/
var luckydraw_sourcePool = [
{ ID: 1, Name: "总经理室-丁当&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 2, Name: "总经理室-柳志坚", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 3, Name: "总经理室-黄宜庚", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 4, Name: "总经理室-刘小军", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 5, Name: "总经理室-赵福俊", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 6, Name: "总经理室-李春&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 7, Name: "总经理室-邓明辉", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 8, Name: "总经理室-陈卓然", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 9, Name: "总经理室-李海峰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 10, Name: "总经理室-余宏&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 11, Name: "总经理室-李文明", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 12, Name: "总经理室-秦旭辉", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 13, Name: "总经理室-孙汉杰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 14, Name: "资产部-叶凌祯", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 15, Name: "资产部-刘文忠", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 16, Name: "中西区-赵晓露", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 17, Name: "中西区-邹敏&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 18, Name: "中西区-刘冰&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 19, Name: "中西区-陈剑&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 20, Name: "中西区-彭若杰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 21, Name: "中西区-范洪超", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 22, Name: "中西区-徐冬&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 23, Name: "中西区-鲁芳芳", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 24, Name: "中西区-戴云&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 25, Name: "中西区-陈坤&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 26, Name: "中西区-邵勇昌", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 27, Name: "中西区-郑荣真", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 28, Name: "中西区-张胜利", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 29, Name: "中西区-魏立尤", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 30, Name: "中西区-曲乃舒", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 31, Name: "中西区-谢小能", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 32, Name: "中西区-杨卓松", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 33, Name: "中西区-戴萌&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 34, Name: "中西区-陆玉&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 35, Name: "中西区-胡文锐", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 36, Name: "中西区-李洁&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 37, Name: "中西区-陈业玮", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 38, Name: "中西区-梁治国", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 39, Name: "中西区-张中刚", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 40, Name: "中西区-王瑛&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 41, Name: "中西区-左琼&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 42, Name: "中西区-程明&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 43, Name: "中西区-严晗&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 44, Name: "中西区-王琦&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 45, Name: "中西区-穆程斌", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 46, Name: "中西区-吴俊&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 47, Name: "中西区-廖玲玲", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 48, Name: "中西区-邹东东", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 49, Name: "中西区-朱山&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 50, Name: "中西区-李剑荣", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 51, Name: "中西区-李宗泽", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 52, Name: "中西区-吴源源", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 53, Name: "中西区-谢芳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 54, Name: "中西区-杨海玲", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 55, Name: "中西区-牛阿娜", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 56, Name: "中西区-沈蕾&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 57, Name: "中西区-刘曦炜", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 58, Name: "中西区-杨小芳", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 59, Name: "中西区-韩飞&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 60, Name: "中西区-闫雪&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 61, Name: "运营部-黄岩松", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 62, Name: "运营部-雷琳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 63, Name: "运营部-林楚娜", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 64, Name: "运营部-段慧敏", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 65, Name: "运营部-陈强&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 66, Name: "运营部-杨慧娟", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 67, Name: "运营部-李佑涵", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 68, Name: "运营部-洪蕾&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 69, Name: "运营部-李蕾俊", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 70, Name: "运营部-张显魁", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 71, Name: "运营部-董瑞萍", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 72, Name: "运营部-陈建峰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 73, Name: "运营部-艾思默", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 74, Name: "运营部-严华&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 75, Name: "运营部-徐凯&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 76, Name: "运营部-李海峰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 77, Name: "运营部-张樱姿", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 78, Name: "运营部-谢致三", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 79, Name: "运营部-朴毅&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 80, Name: "运营部-周悦&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 81, Name: "运营部-蔡丽萍", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 82, Name: "运营部-杨萱&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 83, Name: "系规部-马建国", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 84, Name: "系规部-王劲松", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 85, Name: "系规部-魏欢&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 86, Name: "系规部-张田&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 87, Name: "系规部-戴莉&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 88, Name: "系规部-王豫霞", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 89, Name: "系规部-魏童&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 90, Name: "系规部-陈锦辉", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 91, Name: "系规部-王宇祜", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 92, Name: "系规部-黄国庆", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 93, Name: "系规部-魏丽娟", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 94, Name: "系规部-吴晓雯", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 95, Name: "系规部-秦珍&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 96, Name: "系规部-徐维&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 97, Name: "系规部-韦舒&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 98, Name: "系规部-李雯&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 99, Name: "市场部-谭明秀", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 100, Name: "市场部-王云鹏", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 101, Name: "市场部-季文浩", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 102, Name: "市场部-何希凡", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 103, Name: "市场部-邓岳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 104, Name: "市场部-宋薇&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 105, Name: "市场部-徐英&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 106, Name: "市场部-罗军&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 107, Name: "市场部-顾翀&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 108, Name: "市场部-周立新", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 109, Name: "市场部-杜鹃&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 110, Name: "市场部-吴飞&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 111, Name: "市场部-孔怡&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 112, Name: "市场部-王伟&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 113, Name: "人事部-傅洪波", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 114, Name: "人事部-王文晶", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 115, Name: "人事部-李克亚", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 116, Name: "人事部-喻杰&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 117, Name: "人事部-万颖莹", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 118, Name: "人事部-王浩&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 119, Name: "人事部-李丽媛", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 120, Name: "人事部-闫妍&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 121, Name: "人事部-张人仁", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 122, Name: "人事部-江亮&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 123, Name: "人事部-胡致远", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 124, Name: "人事部-蒋雯&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 125, Name: "人事部-谭科&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 126, Name: "人事部-李雪&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 127, Name: "人事部-关小雄", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 128, Name: "人事部-黄玉娜", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 129, Name: "人事部-陈伟&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 130, Name: "人事部-秦臻&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 131, Name: "人事部-王宝岩", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 132, Name: "人事部-毕胜&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 133, Name: "人事部-张琼文", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 134, Name: "人事部-鞠武志", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 135, Name: "人事部-李银兰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 136, Name: "区拓部-黄智勇", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 137, Name: "区拓部-王树南", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 138, Name: "区拓部-甘瑞华", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 139, Name: "区拓部-傅正茂", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 140, Name: "区拓部-刘定红", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 141, Name: "区拓部-辛乐&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 142, Name: "区拓部-冯冰&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 143, Name: "区拓部-王信锋", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 144, Name: "区拓部-郑丹丹", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 145, Name: "区拓部-吴秋芬", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 146, Name: "区拓部-叶菊荣", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 147, Name: "区拓部-周少帅", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 148, Name: "区拓部-罗慧&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 149, Name: "区拓部-卢淑明", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 150, Name: "区拓部-朱丽娜", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 151, Name: "区拓部-于春雨", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 152, Name: "区拓部-李欢&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 153, Name: "企划部-方如峰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 154, Name: "企划部-商韬&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 155, Name: "企划部-童巍&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 156, Name: "企划部-刘丹凝", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 157, Name: "企划部-刘春晓", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 158, Name: "企划部-樊磊&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 159, Name: "企划部-杨镇宇", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 160, Name: "企划部-夏明&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 161, Name: "企划部-常帅&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 162, Name: "企划部-肖乔&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 163, Name: "企划部-吴珍&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 164, Name: "企划部-唐霨桦", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 165, Name: "企划部-余明锋", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 166, Name: "企划部-张晓明", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 167, Name: "企划部-桂文涓", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 168, Name: "企划部-郑渊&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 169, Name: "企划部-孟萌&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 170, Name: "培训部-郑文珍", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 171, Name: "培训部-梅政&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 172, Name: "培训部-汪扬&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 173, Name: "培训部-张莹&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 174, Name: "培训部-陈怡&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 175, Name: "培训部-刘磊&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 176, Name: "培训部-韩贝贝", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 177, Name: "培训部-冯婧&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 178, Name: "培训部-庞遵强", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 179, Name: "培训部-王硕&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 180, Name: "培训部-王洋&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 181, Name: "培训部-杨睿哲", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 182, Name: "培训部-梅志霞", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 183, Name: "培训部-王红英", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 184, Name: "培训部-莫凌柏", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 185, Name: "培训部-田晓&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 186, Name: "培训部-魏倩&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 187, Name: "培训部-赵青&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 188, Name: "培训部-侯楚键", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 189, Name: "培训部-梁啟亮", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 190, Name: "培训部-袁垚&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 191, Name: "培训部-穆青&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 192, Name: "培训部-康燕&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 193, Name: "培训部-李晓冰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 194, Name: "培训部-李玉磊", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 195, Name: "培训部-于梦&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 196, Name: "培训部-杜玲&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 197, Name: "培训部-丁鹏&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 198, Name: "南&nbsp区-裴双喜", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 199, Name: "南&nbsp区-倪文贵", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 200, Name: "南&nbsp区-高继红", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 201, Name: "南&nbsp区-韩抗抗", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 202, Name: "南&nbsp区-姚敦辰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 203, Name: "南&nbsp区-蓝淑明", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 204, Name: "南&nbsp区-王祎伟", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 205, Name: "南&nbsp区-李咏俊", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 206, Name: "南&nbsp区-熊俊&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 207, Name: "南&nbsp区-欧苗&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 208, Name: "南&nbsp区-甘艳春", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 209, Name: "南&nbsp区-曾健&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 210, Name: "南&nbsp区-方仲强", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 211, Name: "南&nbsp区-朱乐保", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 212, Name: "南&nbsp区-谢振杰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 213, Name: "南&nbsp区-孙鸿雁", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 214, Name: "南&nbsp区-张毅&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 215, Name: "南&nbsp区-李俊廷", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 216, Name: "南&nbsp区-李晓波", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 217, Name: "南&nbsp区-刘文芳", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 218, Name: "南&nbsp区-阙颖&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 219, Name: "南&nbsp区-陈鑫&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 220, Name: "南&nbsp区-卢建菊", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 221, Name: "南&nbsp区-丁志华", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 222, Name: "南&nbsp区-胡宇宁", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 223, Name: "南&nbsp区-梁敏&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 224, Name: "南&nbsp区-聂慧娟", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 225, Name: "南&nbsp区-王小红", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 226, Name: "南&nbsp区-商冬红", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 227, Name: "南&nbsp区-王巍&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 228, Name: "南&nbsp区-王欣&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 229, Name: "南&nbsp区-曾欢&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 230, Name: "南&nbsp区-王晓&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 231, Name: "南&nbsp区-安成德", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 232, Name: "南&nbsp区-石东亮", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 233, Name: "南&nbsp区-马静&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 234, Name: "南&nbsp区-方芳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 235, Name: "南&nbsp区-黄瑜丹", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 236, Name: "南&nbsp区-邢月鑫", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 237, Name: "南&nbsp区-方壹洲", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 238, Name: "南&nbsp区-黄柳溪", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 239, Name: "南&nbsp区-孙建国", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 240, Name: "南&nbsp区-黎淑欣", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 241, Name: "南&nbsp区-黄蓉&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 242, Name: "南&nbsp区-苗宇&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 243, Name: "客开部-宗林&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 244, Name: "客开部-刘波&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 245, Name: "客开部-车跃&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 246, Name: "客开部-徐长妤", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 247, Name: "客开部-田斐&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 248, Name: "客开部-代严&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 249, Name: "客开部-陈莹&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 250, Name: "客开部-周海昌", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 251, Name: "客开部-胡少雯", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 252, Name: "客开部-王东&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 253, Name: "客开部-杨星人", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 254, Name: "客开部-杨璠&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 255, Name: "客开部-张刚&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 256, Name: "客服部-田敏&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 257, Name: "客服部-肖燕燕", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 258, Name: "客服部-苗淑娟", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 259, Name: "客服部-王谢涛", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 260, Name: "客服部-曲悦&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 261, Name: "客服部-熊琳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 262, Name: "客服部-杨飞飞", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 263, Name: "客服部-黄惠巧", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 264, Name: "客服部-于静波", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 265, Name: "客服部-张暐暐", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 266, Name: "客服部-何智勤", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 267, Name: "客服部-魏恒&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 268, Name: "客服部-欧静敏", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 269, Name: "客服部-李鑫&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 270, Name: "客服部-曹昕婷", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 271, Name: "客服部-谢丹&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 272, Name: "客服部-王天玮", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 273, Name: "客服部-吴志鹏", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 274, Name: "客服部-唐鸿宾", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 275, Name: "客服部-胡子平", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 276, Name: "客服部-胡运俊", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 277, Name: "客服部-郑晶晶", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 278, Name: "客服部-舒明&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 279, Name: "客服部-潘建准", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 280, Name: "客服部-王川&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 281, Name: "客服部-吴兆辉", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 282, Name: "客服部-王生&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 283, Name: "客服部-李卫魏", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 284, Name: "客服部-周程程", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 285, Name: "客服部-张艳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 286, Name: "客服部-陈睿睿", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 287, Name: "客服部-王亚子", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 288, Name: "客服部-夏冰&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 289, Name: "客服部-梁羽欢", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 290, Name: "客服部-胡良天", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 291, Name: "客服部-刘进伟", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 292, Name: "客服部-闫玥&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 293, Name: "客服部-易平&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 294, Name: "精算部-谢骏峰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 295, Name: "精算部-冯丽智", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 296, Name: "精算部-刘天略", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 297, Name: "精算部-刘思媛", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 298, Name: "精算部-陈子健", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 299, Name: "精算部-王雪锋", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 300, Name: "精算部-许婉玲", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 301, Name: "精算部-赖欣华", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 302, Name: "精算部-陈兢&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 303, Name: "精算部-王阳洋", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 304, Name: "精算部-张炳文", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 305, Name: "精算部-曹高文", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 306, Name: "精算部-张人旭", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 307, Name: "精算部-彭群&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 308, Name: "精算部-宋琳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 309, Name: "精算部-赵文昊", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 310, Name: "精算部-李慧琴", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 311, Name: "精算部-薛倜&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 312, Name: "精算部-辜质敏", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 313, Name: "精算部-鄢辰光", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 314, Name: "精算部-艾海滨", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 315, Name: "精算部-钟雨珂", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 316, Name: "精算部-陈宇航", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 317, Name: "精算部-黄咏鹏", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 318, Name: "精算部-徐永胜", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 319, Name: "精算部-杨晹&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 320, Name: "精算部-李兵&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 321, Name: "两核部-谭林玉", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 322, Name: "两核部-王新阳", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 323, Name: "两核部-金娟&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 324, Name: "两核部-武瑞雪", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 325, Name: "两核部-靳玉露", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 326, Name: "两核部-江伟玲", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 327, Name: "两核部-邓力涛", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 328, Name: "两核部-肖玮&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 329, Name: "两核部-钟邃&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 330, Name: "两核部-金丹&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 331, Name: "两核部-方游&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 332, Name: "两核部-高萍&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 333, Name: "两核部-谈真&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 334, Name: "两核部-郝晓丽", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 335, Name: "两核部-王娟&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 336, Name: "两核部-刘艳娇", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 337, Name: "两核部-孙钢&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 338, Name: "两核部-郑超&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 339, Name: "两核部-赵莹&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 340, Name: "两核部-张鹏&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 341, Name: "两核部-庞焕雄", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 342, Name: "两核部-褚卫庆", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 343, Name: "两核部-沈晓丹", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 344, Name: "两核部-田香勇", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 345, Name: "两核部-宁玉光", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 346, Name: "合规部-贺广庆", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 347, Name: "合规部-王娟&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 348, Name: "合规部-王道主", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 349, Name: "合规部-方梓鉴", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 350, Name: "合规部-刘甲&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 351, Name: "合规部-刘文力", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 352, Name: "合规部-杨媛&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 353, Name: "合规部-江辉宁", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 354, Name: "合规部-帅艳妮", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 355, Name: "合规部-贺克青", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 356, Name: "合规部-张晴&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 357, Name: "行政部-罗乐&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 358, Name: "行政部-黄新任", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 359, Name: "行政部-黄嘉欣", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 360, Name: "行政部-万捷&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 361, Name: "行政部-王芒&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 362, Name: "行政部-王魏&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 363, Name: "行政部-潘朝刚", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 364, Name: "行政部-邓志清", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 365, Name: "行政部-彭楷&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 366, Name: "行政部-刘金龙", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 367, Name: "行政部-关洪波", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 368, Name: "行政部-李少辉", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 369, Name: "行政部-奉丽枚", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 370, Name: "行政部-刘光凌", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 371, Name: "行政部-秦倩&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 372, Name: "行政部-刘婷婷", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 373, Name: "行政部-郝云香", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 374, Name: "行政部-于斌&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 375, Name: "行政部-张兴兰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 376, Name: "行政部-郑之炎", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 377, Name: "行政部-熊郁林", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 378, Name: "行政部-周七良", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 379, Name: "行政部-徐红&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 380, Name: "行政部-赖正中", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 381, Name: "行政部-乔茹&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 382, Name: "行政部-李卫华", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 383, Name: "行政部-李冬&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 384, Name: "行政部-夏心怡", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 385, Name: "行政部-李劲&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 386, Name: "行政部-李方&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 387, Name: "行政部-甘抒云", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 388, Name: "行政部-蔡卿&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 389, Name: "行政部-张明勇", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 390, Name: "行政部-程莹珺", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 391, Name: "行政部-刘铮铮", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 392, Name: "行政部-郑阳晗", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 393, Name: "产品部-张奇&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 394, Name: "产品部-叶姝丽", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 395, Name: "产品部-陈婷婷", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 396, Name: "产品部-桑影&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 397, Name: "产品部-董婷婷", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 398, Name: "产品部-汪志国", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 399, Name: "产品部-谭佳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 400, Name: "产品部-张升&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 401, Name: "产品部-王宇佼", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 402, Name: "产品部-姜旖&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 403, Name: "产品部-李静华", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 404, Name: "产品部-许景&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 405, Name: "产品部-梁丽青", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 406, Name: "产品部-吴运航", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 407, Name: "产品部-张勍&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 408, Name: "产品部-靳雅楠", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 409, Name: "产品部-张莹&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 410, Name: "产品部-徐丹&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 411, Name: "风管部-张文宪", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 412, Name: "风管部-肖仕奎", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 413, Name: "风管部-张茵&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 414, Name: "风管部-陈政龙", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 415, Name: "风管部-王文玉", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 416, Name: "风管部-肖旗辉", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 417, Name: "风管部-李朋召", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 418, Name: "二元部-吴军&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 419, Name: "二元部-仲崇崇", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 420, Name: "二元部-程凯&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 421, Name: "二元部-刘晓义", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 422, Name: "二元部-王敏&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 423, Name: "二元部-刘红霞", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 424, Name: "二元部-王汇灵", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 425, Name: "二元部-万军&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 426, Name: "董办(深)-刘乐&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 427, Name: "董办(深)-赵伟&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 428, Name: "董办(深)-曾彧敏", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 429, Name: "董办(深)-胡沐&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 430, Name: "董办(深)-汪水山", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 431, Name: "电商部-黄春香", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 432, Name: "电商部-刘良浩", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 433, Name: "电商部-张明&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 434, Name: "电商部-张旗&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 435, Name: "电商部-吴琴&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 436, Name: "电商部-龚婷婷", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 437, Name: "电商部-张久宁", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 438, Name: "电商部-孙鑫&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 439, Name: "电商部-易卓&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 440, Name: "电商部-罗熠&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 441, Name: "电商部-刘强&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 442, Name: "电商部-郑天宇", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 443, Name: "电商部-彭欣&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 444, Name: "电商部-胡龙&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 445, Name: "电商部-周盈&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 446, Name: "电商部-李娟&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 447, Name: "电商部-李雪宁", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 448, Name: "电商部-张洋&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 449, Name: "电商部-李超&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 450, Name: "电商部-曾鑫&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 451, Name: "电商部-熊鹏&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 452, Name: "电商部-李建宇", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 453, Name: "电商部-黄俊&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 454, Name: "电商部-范婷婷", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 455, Name: "电销部-谢进&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 456, Name: "电销部-赵威&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 457, Name: "电销部-彭芳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 458, Name: "电销部-陈依然", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 459, Name: "电销部-吕叶欣", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 460, Name: "电销部-李柏君", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 461, Name: "电销部-张隽鹰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 462, Name: "电销部-凌秋莲", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 463, Name: "电销部-张重皓", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 464, Name: "电销部-成语谋", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 465, Name: "财务部-高嵩&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 466, Name: "财务部-王红&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 467, Name: "财务部-庄玲玲", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 468, Name: "财务部-廖高伟", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 469, Name: "财务部-高雪君", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 470, Name: "财务部-薛国锐", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 471, Name: "财务部-马天&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 472, Name: "财务部-谢欢&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 473, Name: "财务部-张穗苹", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 474, Name: "财务部-任天柱", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 475, Name: "财务部-郝军辉", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 476, Name: "财务部-唐小晓", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 477, Name: "财务部-肖丽萍", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 478, Name: "财务部-张红&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 479, Name: "财务部-屈特诗", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 480, Name: "财务部-许旭东", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 481, Name: "财务部-胡玲玲", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 482, Name: "财务部-潘向贵", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 483, Name: "财务部-贺翠&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 484, Name: "财务部-陈睿&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 485, Name: "财务部-李檬&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 486, Name: "财务部-汤捷&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 487, Name: "财务部-陈晓滔", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 488, Name: "财务部-王璐&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 489, Name: "财务部-芦强&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 490, Name: "财务部-任波&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 491, Name: "财务部-陈蔓红", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 492, Name: "财务部-吕佳&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 493, Name: "财务部-张曼&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 494, Name: "财务部-吕贵杰", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 495, Name: "财务部-张琨&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 496, Name: "财务部-曾雪群", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 497, Name: "财务部-张瑜&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 498, Name: "财务部-冯飞&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 499, Name: "财务部-章剑&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 500, Name: "财务部-于贞坤", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 501, Name: "保费部-马润沛", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 502, Name: "保费部-陈虎&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 503, Name: "保费部-郭刚&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 504, Name: "保费部-张璇&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 505, Name: "保费部-陆桥娥", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 506, Name: "保费部-熊萍&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 507, Name: "保费部-陈家奇", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 508, Name: "保费部-龚洁姿", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 509, Name: "保费部-刘淑琼", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 510, Name: "保费部-李维&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 511, Name: "保费部-赵辉&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 512, Name: "保费部-邓红梅", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 513, Name: "保费部-赵宏艺", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 514, Name: "保费部-夏杨&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 515, Name: "保费部-徐峰&nbsp", Flag: "0", XFlag: "0", YFlag: "0" },
{ ID: 516, Name: "保费部-董怡&nbsp", Flag: "0", XFlag: "0", YFlag: "0" }
];